Update app.py (packages.txt added)
ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "/app/ml_image_classification/app.py", line 5, in <module>
    import tensorflow as tf

DECISION
https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-tensorflow/10579/2

The error message is a bit misleading within the Streamlit app, as the entire container installation is failing (due to ODBC), so nothing gets installed to the container. Then Streamlit starts, you call tensorflow first, and Python tells you it can’t find it.

So try the packages.txt file and if that doesn’t work, we can explore a different solution.